# This is the configuration file for the example website of the Hugo theme
# Astatine (see https://github.com/hugcis/hugo-astatine-theme).
#
# The URL from which the site will be served
baseurl = "/"
# Language used
languageCode = "en-us"
# Website title
title = "Jun Zhao's Group"
# Theme used
theme = "astatine"

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"

# Taxonomies (only tags and categories are supported out of the box but you can
# add more)
[taxonomies]
    category = "categories"  
    tag = "tags"

# Configure permalinks style
[permalinks]
    post = "/:slug/"
    page = "/:slug/"

# Configure main navbar links. They can have a weight to select the order.
# This links to content within the content/home/ folder
[[menu.main]]
    name = "Home"
    url = "/home/"
    weight = -160

# This links to content within the content/post/ folder
[[menu.main]]
    name = "Publication"
    url = "/post/"
    weight = -150

# This links to the page about.md
[[menu.main]]
    name = "Students"
    url = "/about/"
    weight = -110

# Make the tags and categories pages accessible directly from the navbar.
[[menu.main]]
    name = "Projects"
    url = "/tags/"
    weight = -120

[[menu.main]]
    name = "Grants & Awards"
    url = "/categories/"
    weight = -130

# Site wide params and SEO
[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = """The homepage of Astatine. This website is a demo the of the \
    Hugo theme Astatine."""
    # Author of the site
    authorName = "Jack Harkness"
    # Main image for the author. This will be the default image for SEO.
    [params.imgname]
        name = "img/main.jpg"
        # Add an alt description for the image
        alt = "Profile picture"

    # Indicate if you host Katex yourself. Defaults to using the CDN KaTex.
    # hostedKaTex = false

    # Optional: add a twitter handle and mastodon handle for SEO.
    # [params.twitter]
        # name = "@Jack_harkness"
    # [params.mastodon]
        # name = "@jkharkness"
        # host = "mastodon.social"
    
    # Enable link to feed in footer
    blogrss = true

    # Enable pingback and webmention via webmention.io
    # webmention = "hugocisneros.com"


# Sitemap location (default is /sitemap.xml)
[sitemap]
  filename = "sitemap.xml"
